version: 2
updates:
  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - chore

  - package-ecosystem: npm
    directory: /tachimint
    schedule:
      interval: weekly
    target-branch: develop
    labels:
      - chore
    groups:
      typescript-tooling:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "eslint*"
          - "@eslint/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
      deps:
        patterns:
          - "*"
